using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MathBarld;

namespace MathBarld.ProjectEuler
{
    public class Problem2 : MathBarld.ProjectEuler.IProblem
    {
        public string ProblemDescription
        {
            get
            {
                return @"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
            }
        }

        public int GetAnswer()
        {
            int rtw = 0;
            int value = 0;
            int number = 2;
            while(value < 4000000)
            {
                value = Fibonacci.GetFibonacciNumberIterative(number);
                if(value%2==0)
                {
                    rtw += value;
                }

                number++;
            }

            return rtw;
        }
    }
}
